# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f40845dc46f567d244b6d6204535736db1bf56b4b6ab3ebe6206b4ef5f0651abf80899a43a14f11d8fdb93d18d806a93e6aba513b317844a62ee23817f2ba89

test:
  secret_key_base: 77e55a1dc2b5e54108861ffdedf5fdc447ad4f83d0eebeac07f1dc608bab3202e679fde55e884c93969d72c1e1a4c7e1444f08bf9963eb8c4cbf4cca83476cae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
